# Maille (Justin Harvengt : ScSbPd)

In [1]:
!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip


## Données

In [2]:
mp_key = "XJhzTsEnBSh1B3Uh2ARw9cKQZuE9Q90J"
mp_id = "mp-569779"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Vecteurs de base

## Réseau direct

In [8]:
# Réseau direct
réseau_direct = prim_struc.lattice

print("Vue d'ensemble des caractéristiques géométriques :\n")
sga = SpacegroupAnalyzer(prim_struc,0.1)
data = sga.get_primitive_standard_structure()
print(data)
print("\n")

Vue d'ensemble des caractéristiques géométriques :

Full Formula (Sc1 Sb1 Pd1)
Reduced Formula: ScSbPd
abc   :   4.490139   4.490139   4.490139
angles:  60.000000  60.000000  60.000000
pbc   :       True       True       True
Sites (3)
  #  SP       a     b     c
---  ----  ----  ----  ----
  0  Sc    0.5   0.5   0.5
  1  Sb    0     0     0
  2  Pd    0.25  0.25  0.25




In [9]:
# Calcul et affichage des vecteurs de base du réseau direct
a = data.lattice.a
alpha = data.lattice.alpha
print("Vecteurs de base du réseau direct :")
print(SpacegroupAnalyzer(data).find_primitive().lattice.rhombohedral(a,alpha).matrix)
print("\n")
print("Normes des vecteurs :\n", réseau_direct.abc)
print("\n")
print("Angles : \n", réseau_direct.angles)

Vecteurs de base du réseau direct :
[[3.88857456 0.         2.24506957]
 [1.29619152 3.66618325 2.24506957]
 [0.         0.         4.49013913]]


Normes des vecteurs :
 (4.490139293110916, 4.490138800654892, 4.49013962)


Angles : 
 (59.99999396372361, 59.999997591744204, 59.99999914753195)


## Réseau réciproque

In [11]:
# Réseau réciproque
réseau_réciproque = prim_struc.lattice.reciprocal_lattice

# Calcul et affichage des vecteurs de base du réseau réciproque
print("Vecteurs de base du réseau réciproque :\n")
print(sga.find_primitive().lattice.rhombohedral(a,alpha).reciprocal_lattice.matrix)
print("\n")
print("Normes des vecteurs :\n", réseau_réciproque.abc)
print("\n")
print("Angles : \n", réseau_réciproque.angles)

Vecteurs de base du réseau réciproque :

[[ 1.61580683 -0.57127398  0.        ]
 [ 0.          1.71382194  0.        ]
 [-0.80790341 -0.57127398  1.39932976]]


Normes des vecteurs :
 (1.7138218997782049, 1.7138221503961464, 1.7138218645316656)


Angles : 
 (109.4712266962044, 109.4712207716716, 109.47121823108051)


# Données supplémentaires

## Type de maille

In [12]:
# Type de maille
type_de_maille = sga.get_lattice_type()
print("Type de maille :", type_de_maille)

Type de maille : cubic


## Système cristallin

In [13]:
# Système cristallin
système_cristallin = sga.get_crystal_system()
print("Système cristallin :", système_cristallin)

Système cristallin : cubic


## Groupe ponctuel

In [14]:
# Groupe ponctuel
groupe_ponctuel = sga.get_point_group_symbol()
print("Groupe ponctuel :", groupe_ponctuel)

Groupe ponctuel : -43m


# Notes

Le groupe d'espace du ScSbPd est : F4̅3m.
- La lettre "F" signifie que le réseau est "faces centrées"
- Le chiffre "-4" indique la présence d'une roto-inversion d'ordre 4
- Le chiffre "3" nous indique directement que nous avons affaire à une maille cubique et qu'il existe un axe de rotation d'ordre 3
- La lettre "m" indique la présence de plans de symétrie miroirs

Le système cristallin de la cellule primitive est rhomboédrique (= trigonal) car les vecteurs de base ont tous la même norme et le même angle (60°) entre eux.


Les positions de Wyckoff sont fournies ci-dessous : 

$\textbf{Wyckoff	Element	x	y	z}$

4a	Sb	(0	0	0)

4b	Sc	(1/2	0	0)

4c	Pd	(3/4	1/4	3/4)

On a donc 4 sites équivalents pour chaque atome dans la maille cristalline.