# Symétrie : ScSbPd (Harvengt Justin)

In [50]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots


## Downloading

In [51]:
mp_key = "XJhzTsEnBSh1B3Uh2ARw9cKQZuE9Q90J"
mp_id = "mp-569779"

In [52]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

## Opérations de symétrie

In [53]:
# Visualisation des sites d'atomes dans la maille conventionnelle
sites = conv_struc.sites
count = 1
for site in sites:
    print("Site", count, ":\n",site)
    count += 1

# Trois atomes du cristal exprimés via les coordonnées de la maille conventionnelle
posSc = [0.5, 0.5, 0.5] # site 2
posSb = [0.5, 0.0, 0.5] # site 7
posPd = [0.25, 0.75, 0.75] # site 12

# Positions
positions = [("Sc",posSc), ("Sb",posSb), ("Pd",posPd)]

# Visualisation de la cellule
view = quick_view(conv_struc, "packed", conventional = True)
display(view)

Site 1 :
 [3.17500783e+00 0.00000000e+00 1.94413159e-16] Sc
Site 2 :
 [3.17500783 3.17500783 3.17500783] Sc
Site 3 :
 [0.         0.         3.17500783] Sc
Site 4 :
 [5.10580200e-16 3.17500783e+00 1.94413159e-16] Sc
Site 5 :
 [0. 0. 0.] Sb
Site 6 :
 [5.10580200e-16 3.17500783e+00 3.17500783e+00] Sb
Site 7 :
 [3.17500783 0.         3.17500783] Sb
Site 8 :
 [3.17500783e+00 3.17500783e+00 3.88826318e-16] Sb
Site 9 :
 [4.76251174 1.58750391 4.76251174] Pd
Site 10 :
 [4.76251174 4.76251174 1.58750391] Pd
Site 11 :
 [1.58750391 1.58750391 1.58750391] Pd
Site 12 :
 [1.58750391 4.76251174 4.76251174] Pd


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## Symétries

In [54]:
# Visualisation de l'ensemble des opérations de symétrie
print("Visualisation de l'ensemble des opérations de symétrie :")
for i, symmop in enumerate(symmops, start = 1):
    print("Opération", i, ":")
    print("Matrice de rotation :")
    print(symmop.rotation_matrix)
    print("Vecteur de translation :")
    print(symmop.translation_vector, "\n")

Visualisation de l'ensemble des opérations de symétrie :
Opération 1 :
Matrice de rotation :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 2 :
Matrice de rotation :
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 3 :
Matrice de rotation :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 4 :
Matrice de rotation :
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 5 :
Matrice de rotation :
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 6 :
Matrice de rotation :
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 7 :
Matrice de rotation :
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0. 0. 0.] 

Opération 8 :
Matrice de rotation :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Vecteur de translation :
[0. 0. 0.] 

O

### Première opération de symétrie

In [55]:
# Opération 2 sur Sc
print("Matrice de rotation :")
print(symmops[1].rotation_matrix)
print("Vecteur de translation :")
print(symmops[1].translation_vector, "\n")

# Positions initiale et finale
print("Atome :", positions[0][0])
print("Position initiale :", positions[0][1])
print("Position finale :", symmops[1].operate(positions[0][1]), "\n")

# Plot du cristal
view = quick_view(conv_struc)
display(view)
view.script('draw symop 2 {atomno = 2}; select atomno=2; label on; color red')

Matrice de rotation :
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0. 0. 0.] 

Atome : Sc
Position initiale : [0.5, 0.5, 0.5]
Position finale : [ 0.5 -0.5 -0.5] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Deuxième opération de symétrie

In [56]:
# Opération 31 sur Sb
print("Matrice de rotation :")
print(symmops[30].rotation_matrix)
print("Vecteur de translation :")
print(symmops[30].translation_vector, "\n")

# Positions initiale et finale
print("Atome :", positions[1][0])
print("Position initiale :", positions[1][1])
print("Position finale :", symmops[30].operate(positions[1][1]), "\n")

# Plot du cristal
view = quick_view(conv_struc)
display(view)
view.script('draw symop 31 {atomno = 7}; select atomno=7; label on; color red')

Matrice de rotation :
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
Vecteur de translation :
[0.5 0.5 0. ] 

Atome : Sb
Position initiale : [0.5, 0.0, 0.5]
Position finale : [ 0.   0.5 -0.5] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Troisième opération de symétrie

In [57]:
# Opération 88 sur Pd
print("Matrice de rotation :")
print(symmops[87].rotation_matrix)
print("Vecteur de translation :")
print(symmops[87].translation_vector, "\n")

# Positions initiale et finale
print("Atome :", positions[2][0])
print("Position initiale :", positions[2][1])
print("Position finale :", symmops[87].operate(positions[2][1]), "\n")

# Plot du cristal
view = quick_view(conv_struc)
display(view)
view.script('draw symop 88 {atomno = 12}; select atomno=12; label on; color red')

Matrice de rotation :
[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [-1.  0.  0.]]
Vecteur de translation :
[0.  0.5 0.5] 

Atome : Pd
Position initiale : [0.25, 0.75, 0.75]
Position finale : [ 0.75 -0.25  0.25] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))